DROP TABLE IF EXISTS TRADE1;
DROP TABLE IF EXISTS TRADE2;
CREATE TABLE TRADE1 (
	TradeDate	DATE,
	AccountID	STRING,
	Ticker		STRING,
	Quantity	INTEGER,
	Price		FLOAT,
	TradeType	STRING,
	SettlementDate	DATE
);
CREATE TABLE TRADE2 (
	REPORT_DATE	DATE,
	ACCOUNT_ID	STRING,
	SECURITY_TICKER	STRING,
	SHARES		INTEGER,
	MARKET_VALUE	FLOAT,
	SOURCE_SYSTEM	STRING
);
